jobs:
  install-node-example:
    docker:
      - image: 'cimg/node:10.18.0'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
orbs:
  node: circleci/node@4.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
