jobs:
  install-node-example:
    docker:
      - image: 'cimg/node:10.18.0'
    steps:
      - checkout

      - run:
        name: install node
        command: |
          yarn install
      - run:
        name: check
        command: |
          node --version
          npm --version

version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
